export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          wallet_address: string;
          username: string | null;
          bio: string | null;
          avatar_url: string | null;
          reputation_score: number;
          total_spots_created: number;
          total_bounties_created: number;
          total_submissions: number;
          total_earnings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          wallet_address: string;
          username?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          reputation_score?: number;
          total_spots_created?: number;
          total_bounties_created?: number;
          total_submissions?: number;
          total_earnings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          wallet_address?: string;
          username?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          reputation_score?: number;
          total_spots_created?: number;
          total_bounties_created?: number;
          total_submissions?: number;
          total_earnings?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      spots: {
        Row: {
          id: string;
          creator_id: string | null;
          title: string;
          description: string | null;
          location: unknown; // PostGIS geography type
          latitude: number;
          longitude: number;
          address: string | null;
          city: string | null;
          country: string | null;
          spot_type: string | null;
          difficulty: number | null;
          surface_type: string | null;
          accessibility: string | null;
          photos: string[];
          video_preview_url: string | null;
          views_count: number;
          bounties_count: number;
          submissions_count: number;
          is_active: boolean;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          creator_id?: string | null;
          title: string;
          description?: string | null;
          location: unknown;
          latitude: number;
          longitude: number;
          address?: string | null;
          city?: string | null;
          country?: string | null;
          spot_type?: string | null;
          difficulty?: number | null;
          surface_type?: string | null;
          accessibility?: string | null;
          photos?: string[];
          video_preview_url?: string | null;
          views_count?: number;
          bounties_count?: number;
          submissions_count?: number;
          is_active?: boolean;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          creator_id?: string | null;
          title?: string;
          description?: string | null;
          location?: unknown;
          latitude?: number;
          longitude?: number;
          address?: string | null;
          city?: string | null;
          country?: string | null;
          spot_type?: string | null;
          difficulty?: number | null;
          surface_type?: string | null;
          accessibility?: string | null;
          photos?: string[];
          video_preview_url?: string | null;
          views_count?: number;
          bounties_count?: number;
          submissions_count?: number;
          is_active?: boolean;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bounties: {
        Row: {
          id: string;
          on_chain_id: number | null;
          tx_hash: string | null;
          spot_id: string;
          creator_id: string | null;
          trick_name: string;
          description: string | null;
          trick_difficulty: number | null;
          reward_token: string;
          reward_amount: number;
          reward_amount_usd: number | null;
          votes_required: number;
          is_active: boolean;
          winner_id: string | null;
          winning_submission_id: string | null;
          tags: string[];
          created_at: string;
          completed_at: string | null;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          on_chain_id?: number | null;
          tx_hash?: string | null;
          spot_id: string;
          creator_id?: string | null;
          trick_name: string;
          description?: string | null;
          trick_difficulty?: number | null;
          reward_token: string;
          reward_amount: number;
          reward_amount_usd?: number | null;
          votes_required: number;
          is_active?: boolean;
          winner_id?: string | null;
          winning_submission_id?: string | null;
          tags?: string[];
          created_at?: string;
          completed_at?: string | null;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          on_chain_id?: number | null;
          tx_hash?: string | null;
          spot_id?: string;
          creator_id?: string | null;
          trick_name?: string;
          description?: string | null;
          trick_difficulty?: number | null;
          reward_token?: string;
          reward_amount?: number;
          reward_amount_usd?: number | null;
          votes_required?: number;
          is_active?: boolean;
          winner_id?: string | null;
          winning_submission_id?: string | null;
          tags?: string[];
          created_at?: string;
          completed_at?: string | null;
          expires_at?: string | null;
        };
      };
      submissions: {
        Row: {
          id: string;
          on_chain_id: number | null;
          tx_hash: string | null;
          bounty_id: string;
          skater_id: string | null;
          video_url: string;
          video_thumbnail_url: string | null;
          video_duration: number | null;
          votes_up: number;
          votes_down: number;
          vote_score: number;
          status: string;
          is_rewarded: boolean;
          caption: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          on_chain_id?: number | null;
          tx_hash?: string | null;
          bounty_id: string;
          skater_id?: string | null;
          video_url: string;
          video_thumbnail_url?: string | null;
          video_duration?: number | null;
          votes_up?: number;
          votes_down?: number;
          status?: string;
          is_rewarded?: boolean;
          caption?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          on_chain_id?: number | null;
          tx_hash?: string | null;
          bounty_id?: string;
          skater_id?: string | null;
          video_url?: string;
          video_thumbnail_url?: string | null;
          video_duration?: number | null;
          votes_up?: number;
          votes_down?: number;
          status?: string;
          is_rewarded?: boolean;
          caption?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      find_nearby_spots: {
        Args: {
          user_lat: number;
          user_lng: number;
          radius_km: number;
        };
        Returns: Array<{
          id: string;
          title: string;
          distance_km: number;
          latitude: number;
          longitude: number;
          difficulty: number;
          bounties_count: number;
        }>;
      };
    };
  };
};
